dist: trusty
sudo: required

language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: vicervin-github
  token:
    secure: SONAR_TOKEN

script:
  - (cd djangorest; python manage.py test)
